### ISSUE TITLE
[회원가입 페이지 구현] 본인인증 이메일 템플릿 엔진 추가

### ISSUE THREAD

**Issue by Roharui** [GiveUsMoney/FanFixiv-user#36]
> https://github.com/GiveUsMoney/FanFixiv/issues/48 참고

**Task 설명**
본인인증 이메일을 위한 템플릿 엔진을 결정합니다.

**TODO**

- [x] 템플릿 엔진 조사
- [x] 템플릿 엔진 추가
- [x] 이메일 템플릿 추가 후 이메일 확인

**레퍼런스**
- https://blog.huiya.me/m/14

**Comment by Roharui** [comment]
템플릿 엔진은 thymeleaf으로 결정되었습니다.
